/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface AppTimer {
        "src": string;
    }
    interface AppTimerCountdown {
        "stopTimer": () => void;
        "time": number;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppTimerElement extends Components.AppTimer, HTMLStencilElement {
    }
    var HTMLAppTimerElement: {
        prototype: HTMLAppTimerElement;
        new (): HTMLAppTimerElement;
    };
    interface HTMLAppTimerCountdownElement extends Components.AppTimerCountdown, HTMLStencilElement {
    }
    var HTMLAppTimerCountdownElement: {
        prototype: HTMLAppTimerCountdownElement;
        new (): HTMLAppTimerCountdownElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "app-timer": HTMLAppTimerElement;
        "app-timer-countdown": HTMLAppTimerCountdownElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface AppTimer {
        "src"?: string;
    }
    interface AppTimerCountdown {
        "stopTimer"?: () => void;
        "time"?: number;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-root": AppRoot;
        "app-timer": AppTimer;
        "app-timer-countdown": AppTimerCountdown;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-timer": LocalJSX.AppTimer & JSXBase.HTMLAttributes<HTMLAppTimerElement>;
            "app-timer-countdown": LocalJSX.AppTimerCountdown & JSXBase.HTMLAttributes<HTMLAppTimerCountdownElement>;
        }
    }
}
